name: AWS JSII Action
description: "Compiles your AWS CDK Typescript constructs into JavaScript, Python, Java and .Net using the jsii/superchain Docker image."
branding:
  icon: "package"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
