name: "Pull Request"
on:
  push:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "hotfix/[0-9]+.[0-9]+.[0-9]+"
jobs:
  create-pull-request:
    name: Create pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: |
          RELEASE_VERSION=$(echo "$GITHUB_REF" | awk -F / '{print $4}')
          RELEASE_TYPE=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=RELEASE_TYPE::$RELEASE_TYPE"
      - name: Create Pull Request
        id: pull-request-master
        uses: peter-evans/create-pull-request@v2
        with:
          title: ${{ env.RELEASE_TYPE }}/${{ env.RELEASE_VERSION }}
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: ${{ env.RELEASE_TYPE }}/${{ env.RELEASE_VERSION }}
          base: master
          draft: false

      
