name: "Create Release"
on:
  create:
    branches:
      - "release/[0-9]+.[0-9]+.[0-9]+"
      - "hotfix/[0-9]+.[0-9]+.[0-9]+"
jobs:
  draft-new-release:
    name: Draft a new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get release version
        run: |
          RELEASE_VERSION=$(echo "$GITHUB_REF" | awk -F / '{print $4}')
          RELEASE_TYPE=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
          echo "::set-env name=RELEASE_VERSION::$RELEASE_VERSION"
          echo "::set-env name=RELEASE_TYPE::$RELEASE_TYPE"
      - name: Initialize git config
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
      - name: Bump version in package.json
        run: yarn version --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version
      - name: Commit package.json
        id: make-commit
        run: |
          git add package.json
          git commit --message "Bump to version ${{ env.RELEASE_VERSION }}"
          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push changes
        run: git push origin ${{ env.RELEASE_TYPE }}/${{ env.RELEASE_VERSION }}

      
